var token;

function send(url, data, complete) {

    $.ajax({
        type: 'POST',
        url: url,
        data: JSON.stringify(data),
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        processdata: false,
        success: function (responce) {
            ClearInputs();
            complete(responce);
            console.log('succeded!!!');
        },
        error: function () {
            NewCaptcha();
            console.log('failed!!!');
        }
    });
};

$(document).ready(function () {

    var myCaptchaUrl = 'http://localhost:50591/AdDataService.svc/';

    function NewCaptcha() {

        $.getJSON(myCaptchaUrl + 'login', function (responce) { // 1 arg - pass to JSON, 2 - data recieving from Service
            $('#captchaHolder').attr('src', 'http://localhost:50591' + '/Helpers/CaptchaImg/' + responce.image); // set image attribute (src) to <div id"captchaHolder"> and recieving data from Service (image)
            token = responce.token; // recieving data from Service (token)
        });
    }

    NewCaptcha(); // initialize new captcha

    $('#btnSubmit').click(function () {
        var userValue = $('#txtUserValue').val();      // taking value from user  
        var verifyUrl = myCaptchaUrl + "verify?token=" + token + "&value=" + userValue; // compare token and user value with actual data generated by Service

        $.getJSON(verifyUrl, function (responce) {
            if (responce.result) {
                $('#btnInsert').removeClass("disabled")
            }
            else {
                $('#captchaError').css('visibility', 'visible').html('Value is not valid');
                $('#txtUserValue').val('');
                NewCaptcha();
            }
        });
    });

    $('#btnReCaptcha').click(function () {
        $('#txtUserValue').val('');
        NewCaptcha();
    });

    $.validator.setDefaults({
        submitHandler: function () {
            var ad = {
                ItemName: $('#txtItemName').val(),
                Description: $('#txtDesc').val(),
                City: $('#txtCity').val(),
                StartRentDate: $('#txtStartRentDate').val(),
                FinishRentDate: $('#txtFinishRentDate').val(),

                DailyRentPrice: parseFloat($('#txtDailyRentPrice').val()),
                WeeklyRentPrice: parseFloat($('#txtWeeklyRentPrice').val()),
                MonthlyRentPrice: parseFloat($('#txtMonthlyRentPrice').val()),

                CaptchaUserValue: $('#txtUserValue').val(),
                TokenServ: token,
                OwnerName: $('#txtOwnerName').val(),
                PhoneNumber: $('#txtPhoneNumber').val()
            };
            console.log(JSON.stringify(ad));

            send('http://localhost:50591/AdDataService.svc/post/newAd', ad, function () {  //uses ajax to send data
                //alert("!!!");
            });

            
            NewCaptcha();
            $('#btnInsert').addClass("disabled");
            
        }
    });

    $('.form-horisontal').validate({     //"name" as attr required for proper work!
        ignore: ".ignore",               // by defolt ":hidden" (need to change for validating hidden inputs!)
        rules: {
            txtDailyRentPrice: {
                required: true,
                min: 0
            }
        },
        messages: {
            txtDailyRentPrice: {
                required: "Please enter a price",
                min: "Price should be 0 or higher"
            }
        }
    });
})

function ClearInputs() {
    $('#txtItemName').val('');
    $('#txtDesc').val('');
    $('#txtCity').val('');
    $('#txtStartRentDate').val('');
    $('#txtFinishRentDate').val('');

    $('#txtDailyRentPrice').val('');
    $('#txtWeeklyRentPrice').val('');
    $('#txtMonthlyRentPrice').val('');

    $('#txtUserValue').val('');
    $('#txtOwnerName').val('');
    $('#txtPhoneNumber').val('');
}

